CREATE DATABASE QL_BENHNHAN_PKMAT

CREATE TABLE DANGNHAP
(
	TENDANGNHAP VARCHAR(50),
	MATKHAU VARCHAR(50)
)

CREATE TABLE BACSI 
(
	MABS VARCHAR(50) PRIMARY KEY NOT NULL,
	TENBS NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH BIT,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50)
)

CREATE TABLE BENHNHAN
(
	MABN VARCHAR(50) PRIMARY KEY NOT NULL,
	TENBN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH BIT,
	CMND INT,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50)
)

CREATE TABLE HOSOBENHAN
(
	MAHS VARCHAR(50) PRIMARY KEY NOT NULL,
	MABN VARCHAR(50) CONSTRAINT FK_HSBA_MABN FOREIGN KEY REFERENCES BENHNHAN(MABN) NOT NULL,
	MABS VARCHAR(50) CONSTRAINT FK_HSBA_MABS FOREIGN KEY REFERENCES BACSI(MABS) NOT NULL,
	NGAYKHAM DATE,
	TRIEUCHUNG NVARCHAR(MAX),
	CHANDOAN NVARCHAR(MAX),
	NGAYTAIKHAM DATE
	
)

CREATE TABLE DICHVU
(
	MADV VARCHAR(50) PRIMARY KEY NOT NULL,
	TENDV NVARCHAR(50),	
)

CREATE TABLE VIENPHI
(
	MAHD VARCHAR(50) PRIMARY KEY NOT NULL,
	MABN VARCHAR(50) CONSTRAINT FK_VP_MABN FOREIGN KEY REFERENCES BENHNHAN(MABN) NOT NULL,
	NGAYTHANHTOAN DATE,
	TONGVIENPHI FLOAT

)

CREATE TABLE THUOC 
(
	MATHUOC VARCHAR(50) PRIMARY KEY NOT NULL,
	TENTHUOC NVARCHAR(MAX),
	CHIDINH NVARCHAR(MAX),
)

CREATE TABLE DONTHUOC
(
	MADT VARCHAR(50) PRIMARY KEY NOT NULL,
	MABN VARCHAR(50) CONSTRAINT FK_DTH_MABN FOREIGN KEY REFERENCES BENHNHAN(MABN) NOT NULL,
	NGAYLAP DATE,
	TONGTIEN FLOAT
)


CREATE TABLE CTDONTHUOC
(
	MADT VARCHAR(50) CONSTRAINT FK_CTDT_MADT FOREIGN KEY REFERENCES DONTHUOC(MADT) NOT NULL,
	MATHUOC VARCHAR(50) CONSTRAINT FK_CTDT_MT FOREIGN KEY REFERENCES THUOC(MATHUOC) NOT NULL,
	SOLUONG INT,
	CACHDUNG NVARCHAR(MAX),
	GIATHUOC FLOAT,
	THANHTIEN FLOAT,
	CONSTRAINT PK_CTDT_MADT_MT PRIMARY KEY (MADT, MATHUOC)
)

CREATE TABLE CTVIENPHI
(
	MAHD VARCHAR(50) CONSTRAINT FK_CTVP_MAVP FOREIGN KEY REFERENCES VIENPHI(MAHD) NOT NULL,
	MADV VARCHAR(50) CONSTRAINT FK_CTVP_MADV FOREIGN KEY REFERENCES DICHVU(MADV) NOT NULL,	
	SOLUONG INT,
	GIATIEN FLOAT,
	THANHTIEN FLOAT,
	CONSTRAINT PK_CTVP_MAVP_MADV PRIMARY KEY (MAHD, MADV)
)
